import { INTEGRATIONS } from "../integrations";
import { BUILTIN_TOOLS, GUARDRAILS, isHttpTool, isMcpTool, toolId, toolIntegration, toolLabel, withAgentDefaults } from "./agents";
import { frameworkOf, type Framework, type FrameworkId } from "./frameworks";
import type { Plan, PlanAgent } from "./types";

/**
 * Per-framework source for one agent. The code is plausible, readable source for each SDK as of
 * mid-2026; it's generated from the agent's config and never runs inside Architect. None of these
 * SDKs are Architect's own dependencies: they appear only in the generated project.
 */

type Ctx = Pick<Plan, "appName" | "agents">;

const snake = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "") || "agent";
const camel = (s: string) => snake(s).replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const upper = (s: string) => snake(s).toUpperCase();

function header(f: Framework, style: "//" | "#" | "html") {
  const text = `Generated by Architect · ${f.label} · edit freely`;
  return style === "html" ? `<!-- ${text} -->` : `${style} ${text}`;
}

/** A Python triple-quoted string body. */
const pyText = (s: string) => s.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
/** A JS template-literal body. */
const tsText = (s: string) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const indent = (s: string, n: number) => s.replace(/\n/g, `\n${" ".repeat(n)}`);
/** A YAML scalar, quoted only when it has to be. */
const yamlStr = (s: string) => (/^[\w][\w .,'()&/-]*$/.test(s) && !/:\s|\s#/.test(s) ? s : JSON.stringify(s));

type ToolSpec = { tool: string; id: string; fn: string; label: string; description: string; mcp: boolean; env?: string };

function toolSpecs(a: PlanAgent): ToolSpec[] {
  return a.tools.map((tool) => {
    const id = toolId(tool);
    const mcp = isMcpTool(tool);
    const label = toolLabel(tool);
    const builtin = BUILTIN_TOOLS.find((b) => b.name === tool);
    const integration = toolIntegration(tool) ?? INTEGRATIONS.find((i) => i.name === tool);
    const http = isHttpTool(tool);
    const description = builtin
      ? builtin.note
      : mcp
        ? `Tools from the ${label} MCP server.`
        : http
          ? `Calls the ${label} HTTP API with the headers saved in Architect.`
          : integration?.description ?? `Calls ${label}.`;
    const fn = mcp ? `${snake(label)}_mcp` : http ? `${snake(label)}_api` : snake(id);
    return { tool, id, fn, label, description, mcp, env: mcp ? `${upper(label)}_MCP_URL` : undefined };
  });
}

/** Guardrails as plain rules, appended to every framework's system prompt. */
function rules(a: PlanAgent) {
  const list = GUARDRAILS.filter((g) => a.guardrails?.includes(g.id)).map((g) => `- ${g.label}.`);
  return list.length ? `\n\nRules:\n${list.join("\n")}` : "";
}

function prompt(a: PlanAgent) {
  return `${a.instructions.trim()}${rules(a)}`;
}

function handoffNames(a: PlanAgent, ctx: Ctx) {
  return (a.handoffs ?? []).map((id) => ctx.agents.find((x) => x.id === id)).filter((x): x is PlanAgent => !!x);
}

function knowledgeNote(a: PlanAgent) {
  const files = a.knowledge ?? [];
  if (!files.length) return "";
  const chunks = files.reduce((s, f) => s + f.chunks, 0);
  return `Indexed by Architect: ${files.map((f) => f.name).join(", ")} (${chunks} ${chunks === 1 ? "chunk" : "chunks"}).`;
}

// ---------------------------------------------------------------------------------------------
// Lyzr (YAML, hosted)
// ---------------------------------------------------------------------------------------------

function lyzr(a: PlanAgent, f: Framework) {
  const list = (items: string[]) => (items.length ? `\n${items.map((i) => `  - ${i}`).join("\n")}` : " []");
  const knowledge = (a.knowledge ?? []).map((k) => `${yamlStr(k.name)}  # ${k.chunks} ${k.chunks === 1 ? "chunk" : "chunks"}`);
  return `${header(f, "#")}
name: ${yamlStr(a.name)}
framework: lyzr
model: ${a.model}
role: ${yamlStr(a.role)}
instructions: |
  ${indent(a.instructions.trim(), 2)}
tools:${list(a.tools.map(toolId))}
knowledge:${list(knowledge)}
memory:
  type: ${a.memory?.mode === "long-term" ? "long_term" : a.memory?.mode ?? "conversation"}${a.memory?.mode === "conversation" ? `\n  window: ${a.memory.window ?? 20}` : ""}
guardrails:${list(GUARDRAILS.filter((g) => a.guardrails?.includes(g.id)).map((g) => g.code))}
handoffs:${list(a.handoffs ?? [])}
`;
}

// ---------------------------------------------------------------------------------------------
// Python: LangGraph, CrewAI, Google ADK
// ---------------------------------------------------------------------------------------------

const PY_CALL_TOOL = `def call_tool(name: str, **args) -> str:
    """Tool calls go through the app's server, which holds each connection's keys."""
    response = httpx.post(f"{os.environ['ARCHITECT_TOOLS_URL']}/{name}", json=args, timeout=30)
    response.raise_for_status()
    return response.text`;

function pyToolFns(a: PlanAgent, specs: ToolSpec[], decorator: (s: ToolSpec) => string, returns: "str" | "dict") {
  return specs
    .map((s) => {
      const doc = s.id === "knowledge_base" && knowledgeNote(a) ? `${s.description} ${knowledgeNote(a)}` : s.description;
      const body = returns === "dict" ? `{"status": "success", "result": call_tool("${s.id}", query=query)}` : `call_tool("${s.id}", query=query)`;
      return `${decorator(s)}def ${s.fn}(query: str) -> ${returns}:
    """${pyText(doc)}"""
    return ${body}`;
    })
    .join("\n\n\n");
}

function pyHandoffs(a: PlanAgent, ctx: Ctx) {
  const to = handoffNames(a, ctx);
  if (!to.length) return "";
  return `\n\n# The Architect runtime routes handoffs, whichever framework the other agent uses.\nHANDOFFS = [${to.map((t) => `"${t.id}"`).join(", ")}]  # ${to.map((t) => t.name).join(", ")}`;
}

function langgraph(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  const State = `${camel(a.id).replace(/^./, (c) => c.toUpperCase())}State`;
  const memory = a.memory?.mode ?? "conversation";
  const imports = [
    "import os",
    "from typing import Annotated, TypedDict",
    "",
    "import httpx",
    "from langchain_anthropic import ChatAnthropic",
    "from langchain_core.messages import AnyMessage, HumanMessage, SystemMessage",
    ...(specs.length ? ["from langchain_core.tools import tool"] : []),
    ...(memory !== "off" ? ["from langgraph.checkpoint.memory import MemorySaver"] : []),
    "from langgraph.graph import END, StateGraph",
    "from langgraph.graph.message import add_messages",
    ...(specs.length ? ["from langgraph.prebuilt import ToolNode"] : []),
    ...(memory === "long-term" ? ["from langgraph.store.memory import InMemoryStore"] : []),
  ];
  const nodes = specs.map((s) => `graph.add_node("${s.fn}", ToolNode([${s.fn}]))`).join("\n");
  const routes = specs.map((s) => `"${s.fn}": "${s.fn}"`).join(", ");
  const compile =
    memory === "off" ? "graph.compile()" : memory === "long-term" ? "graph.compile(checkpointer=MemorySaver(), store=InMemoryStore())" : "graph.compile(checkpointer=MemorySaver())";
  return `${header(f, "#")}
"""${pyText(a.name)}: ${pyText(a.role)}"""
${imports.join("\n")}

SYSTEM_PROMPT = """${pyText(prompt(a))}"""${pyHandoffs(a, ctx)}


${PY_CALL_TOOL}


class ${State}(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]
${specs.length ? `\n\n${pyToolFns(a, specs, () => "@tool\n", "str")}\n\n\nTOOLS = [${specs.map((s) => s.fn).join(", ")}]\n` : ""}
model = ChatAnthropic(model="${a.model}", temperature=0)${specs.length ? ".bind_tools(TOOLS)" : ""}


def agent(state: ${State}) -> dict:
    reply = model.invoke([SystemMessage(SYSTEM_PROMPT), *state["messages"]])
    return {"messages": [reply]}
${
  specs.length
    ? `

def route(state: ${State}) -> str:
    last = state["messages"][-1]
    calls = getattr(last, "tool_calls", None)
    return calls[0]["name"] if calls else END
`
    : ""
}

graph = StateGraph(${State})
graph.add_node("agent", agent)
${specs.length ? `${nodes}\n` : ""}graph.set_entry_point("agent")
${
  specs.length
    ? `graph.add_conditional_edges("agent", route, {${routes}, END: END})\n${specs.map((s) => `graph.add_edge("${s.fn}", "agent")`).join("\n")}`
    : `graph.add_edge("agent", END)`
}

app = ${compile}


def run(text: str, thread_id: str = "default") -> str:
    result = app.invoke({"messages": [HumanMessage(text)]}${memory === "off" ? "" : ', config={"configurable": {"thread_id": thread_id}}'})
    return result["messages"][-1].content
`;
}

function crewai(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  const v = snake(a.id);
  const memory = (a.memory?.mode ?? "conversation") !== "off";
  return `${header(f, "#")}
"""${pyText(a.name)}: ${pyText(a.role)}"""
import os

import httpx
from crewai import Agent, Crew, Process, Task
${specs.length ? "from crewai.tools import tool\n" : ""}

${PY_CALL_TOOL}
${specs.length ? `\n\n${pyToolFns(a, specs, (s) => `@tool("${s.label}")\n`, "str")}\n` : ""}

${v} = Agent(
    role="${pyText(a.name)}",
    goal="${pyText(a.role)}",
    backstory="""${pyText(prompt(a))}""",
    tools=[${specs.map((s) => s.fn).join(", ")}],
    llm="anthropic/${a.model}",
    memory=${memory ? "True" : "False"},
    allow_delegation=${(a.handoffs ?? []).length ? "True" : "False"},
    verbose=False,
)

task = Task(
    description="{input}",
    expected_output="A short, specific answer${a.guardrails?.includes("cite-sources") ? " that cites its sources" : ""}.",
    agent=${v},
)

crew = Crew(agents=[${v}], tasks=[task], process=Process.sequential, memory=${memory ? "True" : "False"})${pyHandoffs(a, ctx)}


def run(text: str) -> str:
    return str(crew.kickoff(inputs={"input": text}))
`;
}

function googleAdk(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  return `${header(f, "#")}
"""${pyText(a.name)}: ${pyText(a.role)}"""
import os

import httpx
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm


${PY_CALL_TOOL}
${specs.length ? `\n\n${pyToolFns(a, specs, () => "", "dict")}\n` : ""}

root_agent = Agent(
    name="${snake(a.id)}",
    model=LiteLlm(model="anthropic/${a.model}"),
    description="${pyText(a.role)}",
    instruction="""${pyText(prompt(a))}""",
    tools=[${specs.map((s) => s.fn).join(", ")}],
)${pyHandoffs(a, ctx)}
`;
}

// ---------------------------------------------------------------------------------------------
// TypeScript: OpenAI Agents SDK, Claude Agent SDK, Mastra
// ---------------------------------------------------------------------------------------------

const TS_CALL_TOOL = `/** Tool calls go through the app's server, which holds each connection's keys. */
async function callTool(name: string, args: Record<string, unknown>): Promise<string> {
  const res = await fetch(\`\${process.env.ARCHITECT_TOOLS_URL}/\${name}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(args),
  });
  if (!res.ok) throw new Error(\`\${name} failed: \${res.status}\`);
  return res.text();
}`;

function tsHandoffs(a: PlanAgent, ctx: Ctx) {
  const to = handoffNames(a, ctx);
  if (!to.length) return "";
  return `\n\n/** The Architect runtime routes handoffs, whichever framework the other agent uses. */\nexport const handoffs = [${to.map((t) => `"${t.id}"`).join(", ")}] as const;`;
}

function tsDescription(a: PlanAgent, s: ToolSpec) {
  return JSON.stringify(s.id === "knowledge_base" && knowledgeNote(a) ? `${s.description} ${knowledgeNote(a)}` : s.description);
}

function openaiAgents(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  const v = camel(a.id);
  const tools = specs
    .map(
      (s) => `const ${camel(s.fn)} = tool({
  name: "${s.fn}",
  description: ${tsDescription(a, s)},
  parameters: z.object({ query: z.string() }),
  execute: ({ query }) => callTool("${s.id}", { query }),
});`,
    )
    .join("\n\n");
  return `${header(f, "//")}
import { anthropic } from "@ai-sdk/anthropic";
import { Agent, run as runAgent${specs.length ? ", tool" : ""} } from "@openai/agents";
import { aisdk } from "@openai/agents-extensions";
${specs.length ? 'import { z } from "zod";\n' : ""}
${TS_CALL_TOOL}
${tools ? `\n${tools}\n` : ""}
/** ${a.name}: ${a.role} */
export const ${v} = new Agent({
  name: ${JSON.stringify(a.name)},
  instructions: \`${tsText(prompt(a))}\`,
  model: aisdk(anthropic("${a.model}")),
  tools: [${specs.map((s) => camel(s.fn)).join(", ")}],
});${tsHandoffs(a, ctx)}

export async function run(input: string): Promise<string> {
  const result = await runAgent(${v}, input);
  return String(result.finalOutput ?? "");
}
`;
}

function claudeAgentSdk(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  const custom = specs.filter((s) => !s.mcp && s.id !== "web_search");
  const mcp = specs.filter((s) => s.mcp);
  const server = `${snake(a.id).replace(/_/g, "-")}-tools`;
  const allowed = [
    ...(specs.some((s) => s.id === "web_search") ? ['"WebSearch"'] : []),
    ...custom.map((s) => `"mcp__${server}__${s.fn}"`),
    ...mcp.map((s) => `"mcp__${snake(s.label)}"`),
  ];
  const servers = [
    ...(custom.length ? [`"${server}": tools`] : []),
    ...mcp.map((s) => `${snake(s.label)}: { type: "http", url: process.env.${s.env}! }`),
  ];
  return `${header(f, "//")}
import { ${custom.length ? "createSdkMcpServer, " : ""}query${custom.length ? ", tool" : ""} } from "@anthropic-ai/claude-agent-sdk";
${custom.length ? 'import { z } from "zod";\n' : ""}
const SYSTEM_PROMPT = \`${tsText(prompt(a))}\`;
${
  custom.length
    ? `
${TS_CALL_TOOL}

const tools = createSdkMcpServer({
  name: "${server}",
  version: "1.0.0",
  tools: [
${custom
  .map(
    (s) => `    tool("${s.fn}", ${tsDescription(a, s)}, { query: z.string() }, async ({ query }) => ({
      content: [{ type: "text", text: await callTool("${s.id}", { query }) }],
    })),`,
  )
  .join("\n")}
  ],
});`
    : ""
}${tsHandoffs(a, ctx)}

/** Runs ${a.name} on one input and returns its final answer. */
export async function run(input: string): Promise<string> {
  let answer = "";
  for await (const message of query({
    prompt: input,
    options: {
      systemPrompt: SYSTEM_PROMPT,
      model: "${a.model}",
${servers.length ? `      mcpServers: { ${servers.join(", ")} },\n` : ""}      allowedTools: [${allowed.join(", ")}],
      maxTurns: 8,
    },
  })) {
    if (message.type === "result" && message.subtype === "success") answer = message.result;
  }
  return answer;
}
`;
}

function mastra(a: PlanAgent, f: Framework, ctx: Ctx) {
  const specs = toolSpecs(a);
  const v = `${camel(a.id)}Agent`;
  const memory = a.memory?.mode ?? "conversation";
  const tools = specs
    .map(
      (s) => `const ${camel(s.fn)} = createTool({
  id: "${s.fn}",
  description: ${tsDescription(a, s)},
  inputSchema: z.object({ query: z.string() }),
  execute: async ({ context }) => callTool("${s.id}", { query: context.query }),
});`,
    )
    .join("\n\n");
  const mem =
    memory === "off"
      ? ""
      : memory === "long-term"
        ? "\n  memory: new Memory({ options: { lastMessages: 20, semanticRecall: true, workingMemory: { enabled: true } } }),"
        : `\n  memory: new Memory({ options: { lastMessages: ${a.memory?.window ?? 20} } }),`;
  return `${header(f, "//")}
import { anthropic } from "@ai-sdk/anthropic";
import { Agent } from "@mastra/core/agent";
${specs.length ? 'import { createTool } from "@mastra/core/tools";\n' : ""}${memory !== "off" ? 'import { Memory } from "@mastra/memory";\n' : ""}${specs.length ? 'import { z } from "zod";\n' : ""}
${specs.length ? `${TS_CALL_TOOL}\n\n${tools}\n\n` : ""}/** ${a.name}: ${a.role} */
export const ${v} = new Agent({
  name: ${JSON.stringify(a.name)},
  instructions: \`${tsText(prompt(a))}\`,
  model: anthropic("${a.model}"),
  tools: { ${specs.map((s) => camel(s.fn)).join(", ")} },${mem}
});${tsHandoffs(a, ctx)}

export async function run(input: string): Promise<string> {
  const result = await ${v}.generate(input);
  return result.text;
}
`;
}

// ---------------------------------------------------------------------------------------------
// GitAgent: the agent as plain files
// ---------------------------------------------------------------------------------------------

function gitagent(a: PlanAgent, f: Framework, ctx: Ctx, dir: string): Record<string, string> {
  const specs = toolSpecs(a);
  const skills = specs.length ? specs.map((s) => ({ file: `skills/${s.fn.replace(/_/g, "-")}.md`, spec: s as ToolSpec | null })) : [{ file: "skills/respond.md", spec: null }];
  const to = handoffNames(a, ctx);
  const h = header(f, "html");
  const out: Record<string, string> = {};
  out[`${dir}/agent.yaml`] = `${header(f, "#")}
name: ${yamlStr(a.name)}
version: 0.1.0
model: ${a.model}
soul: SOUL.md
rules: RULES.md
duties: DUTIES.md
skills:
${skills.map((s) => `  - ${s.file}`).join("\n")}
memory:
  type: ${a.memory?.mode === "long-term" ? "long_term" : a.memory?.mode ?? "conversation"}${a.memory?.mode === "conversation" ? `\n  window: ${a.memory.window ?? 20}` : ""}
  path: memory/
knowledge: knowledge/
handoffs:${to.length ? `\n${to.map((t) => `  - ${t.id}`).join("\n")}` : " []"}
`;
  out[`${dir}/SOUL.md`] = `${h}
# ${a.name}

${a.role}

## Who I am

${a.instructions.trim()}

## How I sound

Plain, specific and brief. I say which source I used, and I say so when I'm not sure.
`;
  const rulesList = GUARDRAILS.filter((g) => a.guardrails?.includes(g.id));
  out[`${dir}/RULES.md`] = `${h}
# Rules

${rulesList.length ? rulesList.map((g, i) => `${i + 1}. ${g.label}.`).join("\n") : "No extra rules yet. Add one per line; the runtime checks them before every reply."}
${rulesList.length + 1}. Never reveal keys, tokens or anything in the environment.
`;
  out[`${dir}/DUTIES.md`] = `${h}
# Duties

- ${a.role}
${specs.map((s) => `- Use ${s.label} when it helps (see \`${skills.find((k) => k.spec === s)?.file}\`).`).join("\n")}
${to.length ? `\n## Handoffs\n\n${to.map((t) => `- Hand work to **${t.name}** when it's their job: ${t.role.charAt(0).toLowerCase()}${t.role.slice(1)}`).join("\n")}\n` : ""}`;
  for (const s of skills) {
    out[`${dir}/${s.file}`] = s.spec
      ? `${h}
# ${s.spec.label}

${s.spec.description}

- Tool: \`${s.spec.id}\`
- Input: a plain-language query
- Output: text the agent can quote or summarise
`
      : `${h}
# Respond

Answer the request directly. Keep it short, and ask one clarifying question when the request is ambiguous.
`;
  }
  out[`${dir}/memory/.gitkeep`] = "";
  const files = a.knowledge ?? [];
  out[`${dir}/knowledge/README.md`] = `${h}
# Knowledge

${files.length ? `${files.map((k) => `- ${k.name} · ${k.chunks} ${k.chunks === 1 ? "chunk" : "chunks"}`).join("\n")}\n\nArchitect keeps the indexed chunks; drop originals here to version them with the agent.` : "No files yet. Add documents here and Architect indexes them for this agent."}
`;
  return out;
}

// ---------------------------------------------------------------------------------------------

/** The files one agent contributes to the project, keyed by path. */
export function agentFiles(agent: PlanAgent, ctx: Ctx): Record<string, string> {
  const a = withAgentDefaults(agent);
  const f = frameworkOf(a.framework);
  switch (f.id) {
    case "langgraph":
      return { [`agents/${a.id}.py`]: langgraph(a, f, ctx) };
    case "crewai":
      return { [`agents/${a.id}.py`]: crewai(a, f, ctx) };
    case "google-adk":
      return { [`agents/${a.id}/__init__.py`]: `${header(f, "#")}\nfrom . import agent\n`, [`agents/${a.id}/agent.py`]: googleAdk(a, f, ctx) };
    case "openai-agents":
      return { [`agents/${a.id}.ts`]: openaiAgents(a, f, ctx) };
    case "claude-agent-sdk":
      return { [`agents/${a.id}.ts`]: claudeAgentSdk(a, f, ctx) };
    case "mastra":
      return { [`src/mastra/agents/${a.id}.ts`]: mastra(a, f, ctx) };
    case "gitagent":
      return gitagent(a, f, ctx, `agents/${a.id}`);
    default:
      return { [`agents/${a.id}.yaml`]: lyzr(a, f) };
  }
}

/** The file that best represents an agent, for "Open in Code tab". */
export function agentEntry(agent: PlanAgent): string {
  const f = frameworkOf(agent.framework).id;
  const id = agent.id;
  const entries: Record<FrameworkId, string> = {
    lyzr: `agents/${id}.yaml`,
    langgraph: `agents/${id}.py`,
    crewai: `agents/${id}.py`,
    "google-adk": `agents/${id}/agent.py`,
    "openai-agents": `agents/${id}.ts`,
    "claude-agent-sdk": `agents/${id}.ts`,
    mastra: `src/mastra/agents/${id}.ts`,
    gitagent: `agents/${id}/SOUL.md`,
  };
  return entries[f];
}

/** Python and npm packages the plan's agent frameworks need. */
export function agentPackages(plan: Pick<Plan, "agents">) {
  const python = new Set<string>();
  const node = new Set<string>();
  for (const a of plan.agents) {
    const f = frameworkOf(a.framework);
    if (f.language === "Python") {
      f.packages.forEach((p) => python.add(p));
      python.add("httpx==0.28.1");
    } else if (f.language === "TypeScript") {
      f.packages.forEach((p) => node.add(p));
      if (f.id === "openai-agents") ["@openai/agents-extensions@^0.1.0", "@ai-sdk/anthropic@^2.0.0"].forEach((p) => node.add(p));
    }
  }
  return { python: [...python].sort(), node: [...node].sort() };
}
