import { APP_THEMES } from "./themes";
import type { Plan, PlanAgent, PlanCollection, PlanPage } from "./types";

/**
 * Turns a plan into the files of a small but real-looking project. Output is deterministic, so a
 * plan change regenerates exactly the files it affects and the version diff stays honest.
 */

export type Stack = "react-vite" | "nextjs" | "fastapi-react";

const pascal = (s: string) => {
  const p = s
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
  return /^[0-9]/.test(p) ? `Page${p}` : p || "Page";
};
const camel = (s: string) => {
  const p = pascal(s);
  return p[0].toLowerCase() + p.slice(1);
};
const json = (v: unknown) => JSON.stringify(v, null, 2);

function tsType(t: string) {
  return t === "number" || t === "money" ? "number" : "string";
}

// ---------------------------------------------------------------------------------------------
// Shared pieces
// ---------------------------------------------------------------------------------------------

function themeCss(plan: Plan) {
  const t = APP_THEMES[plan.ui.theme];
  const v = t.vars;
  return `/* ${t.label} theme, generated by Architect. Change it from the chat: "use the Midnight theme". */
:root {
  --bg: ${v.bg};
  --surface: ${v.surface};
  --sunken: ${v.sunken};
  --text: ${v.text};
  --muted: ${v.muted};
  --border: ${v.border};
  --accent: ${v.accent};
  --accent-text: ${v.accentText};
  --accent-soft: ${v.accentSoft};
  --success: ${v.success};
  --warning: ${v.warning};
  --danger: ${v.danger};
  --radius: ${t.radius}px;
  --border-width: ${t.borderWidth}px;
  --shadow: ${t.shadow};
  color-scheme: ${t.dark ? "dark" : "light"};
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: "Inter", ui-sans-serif, system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3 {
  font-family: ${t.headingFont === "serif" ? '"Instrument Serif", Georgia, serif' : '"Inter", ui-sans-serif, system-ui, sans-serif'};
  ${t.headingCase === "upper" ? "text-transform: uppercase;\n  letter-spacing: -0.01em;" : "letter-spacing: -0.02em;"}
}

.card {
  background: var(--surface);
  border: var(--border-width) solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}

.button {
  background: var(--accent);
  color: var(--accent-text);
  border: 0;
  border-radius: var(--radius);
  padding: 8px 14px;
  font-weight: 600;
}
`;
}

function dataFile(c: PlanCollection, importPath = "") {
  const typeName = pascal(c.singular);
  const fields = c.fields.map((f) => `  ${f.key}: ${tsType(f.type)};`).join("\n");
  const statusValues = c.statusField ? Array.from(new Set(c.rows.map((r) => String(r[c.statusField!])))).filter(Boolean) : [];
  return `${importPath}export type ${typeName} = {
  id: string;
${fields}
};
${
  statusValues.length
    ? `
export const ${camel(c.singular)}Statuses = ${JSON.stringify(statusValues)} as const;
`
    : ""
}
/** Sample ${c.name.toLowerCase()} so the app has something to show before real data arrives. */
export const ${camel(c.name)}: ${typeName}[] = ${json(c.rows.map((r, i) => ({ id: `${c.id}_${i + 1}`, ...r })))};
`;
}

function agentYaml(a: PlanAgent) {
  const tools = a.tools.length ? a.tools.map((t) => `  - ${t}`).join("\n") : "  []";
  return `# ${a.name} agent
name: ${a.name}
framework: ${a.framework}
model: ${a.model}
role: ${a.role}
instructions: |
  ${a.instructions.replace(/\n/g, "\n  ")}
tools:
${tools}
memory:
  type: conversation
  window: 20
guardrails:
  - Never send external messages without an approval step unless the plan says so.
  - Cite the source for any factual claim.
`;
}

function agentsClient(plan: Plan, endpoint: string) {
  const ids = plan.agents.map((a) => `"${a.id}"`).join(" | ") || "string";
  return `export type AgentId = ${ids};

export type AgentRun = {
  output: string;
  trace: { step: string; ms: number }[];
};

/**
 * Runs an agent on the server. Keys stay server-side; the browser only ever sees the output.
 */
export async function runAgent(agent: AgentId, input: string, context?: Record<string, unknown>): Promise<AgentRun> {
  const res = await fetch(\`${endpoint}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ input, context }),
  });
  if (!res.ok) throw new Error(\`Agent \${agent} failed: \${res.status}\`);
  return res.json();
}
`;
}

// ---------------------------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------------------------

function pageComponent(page: PlanPage, plan: Plan, paths: { data: string; lib: string; components: string }) {
  const name = pascal(page.name);
  const c = plan.data.find((d) => d.id === page.collection) ?? plan.data[0];
  const agent = plan.agents.find((a) => a.id === page.agent) ?? plan.agents[0];
  const dataImport = c ? `import { ${camel(c.name)} } from "${paths.data}/${c.id}";\n` : "";
  const agentImport = agent ? `import { runAgent } from "${paths.lib}/agents";\n` : "";
  const header = `      <header className="page-header">
        <h1>${page.name}</h1>
        <p>${page.purpose}</p>
      </header>`;

  switch (page.kind) {
    case "dashboard": {
      const money = c?.fields.find((f) => f.type === "money");
      return `import { useMemo } from "react";
${dataImport}import { StatCard } from "${paths.components}/StatCard";
import { StatusPill } from "${paths.components}/StatusPill";

export default function ${name}() {
  const rows = ${c ? camel(c.name) : "[]"};
  const byStatus = useMemo(() => {
    const counts = new Map<string, number>();
    for (const row of rows) counts.set(${c?.statusField ? `row.${c.statusField}` : '"All"'}, (counts.get(${c?.statusField ? `row.${c.statusField}` : '"All"'}) ?? 0) + 1);
    return [...counts.entries()];
  }, [rows]);

  return (
    <div className="page">
${header}
      <section className="stats">
        <StatCard label="Total ${c?.name.toLowerCase() ?? "items"}" value={rows.length} />
${byStatus_tiles(c)}${money ? `        <StatCard label="Total ${money.label.toLowerCase()}" value={rows.reduce((sum, r) => sum + r.${money.key}, 0)} format="money" />\n` : ""}      </section>

      <section className="card">
        <h2>By ${c?.statusField ?? "status"}</h2>
        <ul className="bars">
          {byStatus.map(([status, count]) => (
            <li key={status}>
              <StatusPill value={status} />
              <span className="bar" style={{ width: \`\${(count / rows.length) * 100}%\` }} />
              <span>{count}</span>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
`;
    }
    case "list": {
      const cols = c?.fields.slice(0, 5) ?? [];
      return `import { useMemo, useState } from "react";
${dataImport}${agentImport}import { StatusPill } from "${paths.components}/StatusPill";

export default function ${name}() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [answer, setAnswer] = useState<string>("");

  const rows = useMemo(
    () =>
      ${c ? camel(c.name) : "[]"}.filter((row) =>
        Object.values(row).some((value) => String(value).toLowerCase().includes(query.toLowerCase())),
      ),
    [query],
  );

  async function ask(id: string) {
    setSelected(id);
    const row = rows.find((r) => r.id === id);
    ${agent ? `const run = await runAgent("${agent.id}", "Summarise this ${c?.singular.toLowerCase() ?? "item"} and suggest the next step.", { row });
    setAnswer(run.output);` : "setAnswer(JSON.stringify(row));"}
  }

  return (
    <div className="page">
${header}
${plan.ui.search ? `      <input className="search" placeholder="Search ${c?.name.toLowerCase() ?? "items"}" value={query} onChange={(e) => setQuery(e.target.value)} />\n` : ""}      <table className="card table">
        <thead>
          <tr>
${cols.map((f) => `            <th>${f.label}</th>`).join("\n")}
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id} onClick={() => ask(row.id)} aria-selected={selected === row.id}>
${cols.map((f) => (f.type === "status" ? `              <td><StatusPill value={row.${f.key}} /></td>` : `              <td>{row.${f.key}}</td>`)).join("\n")}
            </tr>
          ))}
        </tbody>
      </table>

      {answer && <aside className="card answer">{answer}</aside>}
    </div>
  );
}
`;
    }
    case "workbench":
      return `import { useState } from "react";
${dataImport}${agentImport}
export default function ${name}() {
  const items = ${c ? camel(c.name) : "[]"};
  const [current, setCurrent] = useState(items[0]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);

  async function generate() {
    setBusy(true);
    const run = await runAgent("${agent?.id ?? "assistant"}", "Draft a response for this ${c?.singular.toLowerCase() ?? "item"}.", { item: current });
    setDraft(run.output);
    setBusy(false);
  }

  return (
    <div className="page workbench">
${header}
      <nav className="card list">
        {items.map((item) => (
          <button key={item.id} onClick={() => setCurrent(item)} aria-current={item.id === current?.id}>
            {item.${c?.titleField ?? "id"}}
          </button>
        ))}
      </nav>
      <section className="card">
        <h2>{current?.${c?.titleField ?? "id"}}</h2>
        <button className="button" onClick={generate} disabled={busy}>
          {busy ? "${agent?.name ?? "Agent"} is writing…" : "Draft with ${agent?.name ?? "the agent"}"}
        </button>
        <textarea value={draft} onChange={(e) => setDraft(e.target.value)} rows={12} />
        <div className="actions">
          <button className="button">Approve</button>
          <button onClick={generate}>Regenerate</button>
        </div>
      </section>
    </div>
  );
}
`;
    case "chat":
      return `import { useState } from "react";
${agentImport}
type Message = { role: "user" | "agent"; text: string };

export default function ${name}() {
  const [messages, setMessages] = useState<Message[]>([
    { role: "agent", text: "Hi! I'm ${agent?.name ?? "your assistant"}. ${agent?.role ?? ""}" },
  ]);
  const [input, setInput] = useState("");

  async function send() {
    const text = input.trim();
    if (!text) return;
    setMessages((m) => [...m, { role: "user", text }]);
    setInput("");
    const run = await runAgent("${agent?.id ?? "assistant"}", text);
    setMessages((m) => [...m, { role: "agent", text: run.output }]);
  }

  return (
    <div className="page chat">
${header}
      <ol className="messages">
        {messages.map((m, i) => (
          <li key={i} className={m.role}>{m.text}</li>
        ))}
      </ol>
      <form onSubmit={(e) => { e.preventDefault(); send(); }}>
        <input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask ${agent?.name ?? "the assistant"} anything…" />
        <button className="button">Send</button>
      </form>
    </div>
  );
}
`;
    case "run": {
      const pipeline = plan.agents.map((a) => `"${a.id}"`).join(", ");
      return `import { useState } from "react";
${agentImport}
const PIPELINE = [${pipeline}] as const;

export default function ${name}() {
  const [input, setInput] = useState("");
  const [step, setStep] = useState<number | null>(null);
  const [result, setResult] = useState("");

  async function run() {
    let context = input;
    for (let i = 0; i < PIPELINE.length; i++) {
      setStep(i);
      const out = await runAgent(PIPELINE[i], context);
      context = out.output;
    }
    setStep(null);
    setResult(context);
  }

  return (
    <div className="page">
${header}
      <label className="card field">
        <span>${page.input?.label ?? "Input"}</span>
        <textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="${page.input?.placeholder ?? ""}" rows={5} />
      </label>
      <button className="button" onClick={run} disabled={!input || step !== null}>
        {step === null ? "${page.input?.cta ?? "Run"}" : \`Running \${PIPELINE[step]}…\`}
      </button>
      {result && <article className="card result">{result}</article>}
    </div>
  );
}
`;
    }
    case "settings":
      return `const INTEGRATIONS = ${JSON.stringify(plan.integrations)};

export default function ${name}() {
  return (
    <div className="page">
${header}
      <section className="card">
        <h2>Connections</h2>
        <ul>
          {INTEGRATIONS.map((name) => (
            <li key={name}>
              {name} <button>Manage</button>
            </li>
          ))}
        </ul>
      </section>
      <section className="card">
        <h2>Notifications</h2>
        <label><input type="checkbox" defaultChecked /> Email me a daily summary</label>
        <label><input type="checkbox" /> Notify me when an agent needs approval</label>
      </section>
    </div>
  );
}
`;
  }
}

function byStatus_tiles(c?: PlanCollection) {
  if (!c?.statusField) return "";
  const first = String(c.rows[0]?.[c.statusField] ?? "");
  if (!first) return "";
  return `        <StatCard label="${first}" value={rows.filter((r) => r.${c.statusField} === "${first}").length} tone="accent" />\n`;
}

function statusPill() {
  return `const TONES: Record<string, string> = {
  urgent: "danger", high: "danger", overdue: "danger", exception: "danger", blocked: "danger", rejected: "danger",
  done: "success", paid: "success", sent: "success", mastered: "success", ok: "success", indexed: "success", clean: "success",
  "in progress": "warning", review: "warning", "needs review": "warning", learning: "warning", medium: "warning",
};

export function StatusPill({ value }: { value: string }) {
  const tone = TONES[value.toLowerCase()] ?? "neutral";
  return <span className={\`pill pill-\${tone}\`}>{value}</span>;
}
`;
}

function statCard() {
  return `const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function StatCard({ label, value, format, tone }: { label: string; value: number; format?: "money"; tone?: "accent" }) {
  return (
    <div className={\`card stat \${tone ?? ""}\`}>
      <span>{label}</span>
      <strong>{format === "money" ? money.format(value) : value}</strong>
    </div>
  );
}
`;
}

function layout(plan: Plan, routeFor: (p: PlanPage) => string, linkImport: string, linkTag: "Link" | "NavLink") {
  return `${linkImport}
const NAV = [
${plan.pages.map((p) => `  { to: "${routeFor(p)}", label: "${p.name}" },`).join("\n")}
];

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="app">
      <aside className="sidebar">
        <strong className="brand">${plan.appName}</strong>
        <nav>
          {NAV.map((item) => (
            <${linkTag} key={item.to} ${linkTag === "Link" ? "href" : "to"}={item.to}>
              {item.label}
            </${linkTag}>
          ))}
        </nav>
      </aside>
      <main>
${plan.ui.banner ? `        <div className="banner">${plan.ui.banner}</div>\n` : ""}        {children}
      </main>
    </div>
  );
}
`;
}

function readme(plan: Plan, stack: Stack) {
  const run =
    stack === "fastapi-react"
      ? "```bash\ncd backend && pip install -r requirements.txt && uvicorn main:app --reload\ncd frontend && npm install && npm run dev\n```"
      : "```bash\nnpm install\nnpm run dev\n```";
  return `# ${plan.appName}

${plan.tagline}

${plan.overview}

## Pages

${plan.pages.map((p) => `- **${p.name}**: ${p.purpose}`).join("\n")}

## Agents

| Agent | Role | Framework | Tools |
| --- | --- | --- | --- |
${plan.agents.map((a) => `| ${a.name} | ${a.role} | ${a.framework} | ${a.tools.join(", ") || "none"} |`).join("\n")}

## Run it locally

${run}

Agent definitions live in \`agents/\`. Built with Architect.
`;
}

// ---------------------------------------------------------------------------------------------
// Stacks
// ---------------------------------------------------------------------------------------------

function reactVite(plan: Plan, base = ""): Record<string, string> {
  const files: Record<string, string> = {};
  const p = (path: string) => `${base}${path}`;
  const route = (pg: PlanPage) => (pg === plan.pages[0] ? "/" : `/${pg.id}`);

  files[p("package.json")] = json({
    name: plan.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    private: true,
    version: "0.1.0",
    type: "module",
    scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
    dependencies: { react: "^19.2.0", "react-dom": "^19.2.0", "react-router-dom": "^7.9.0" },
    devDependencies: { "@vitejs/plugin-react": "^5.0.0", typescript: "^5.9.0", vite: "^7.1.0" },
  }) + "\n";
  files[p("index.html")] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${plan.appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  files[p("vite.config.ts")] = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { proxy: { "/api": "http://localhost:8000" } },
});
`;
  files[p("tsconfig.json")] = json({
    compilerOptions: { target: "ES2022", lib: ["ES2022", "DOM"], jsx: "react-jsx", module: "ESNext", moduleResolution: "bundler", strict: true, skipLibCheck: true },
    include: ["src"],
  }) + "\n";
  files[p("src/main.tsx")] = `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./theme.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
`;
  files[p("src/App.tsx")] = `import { Route, Routes } from "react-router-dom";
import { Layout } from "./components/Layout";
${plan.pages.map((pg) => `import ${pascal(pg.name)} from "./pages/${pascal(pg.name)}";`).join("\n")}

export default function App() {
  return (
    <Layout>
      <Routes>
${plan.pages.map((pg) => `        <Route path="${route(pg)}" element={<${pascal(pg.name)} />} />`).join("\n")}
      </Routes>
    </Layout>
  );
}
`;
  files[p("src/theme.css")] = themeCss(plan);
  files[p("src/components/Layout.tsx")] = layout(plan, route, 'import { NavLink } from "react-router-dom";\n', "NavLink");
  files[p("src/components/StatusPill.tsx")] = statusPill();
  files[p("src/components/StatCard.tsx")] = statCard();
  files[p("src/lib/agents.ts")] = agentsClient(plan, "/api/agents/${agent}/run");
  for (const c of plan.data) files[p(`src/data/${c.id}.ts`)] = dataFile(c);
  for (const pg of plan.pages) {
    files[p(`src/pages/${pascal(pg.name)}.tsx`)] = pageComponent(pg, plan, { data: "../data", lib: "../lib", components: "../components" });
  }
  return files;
}

function nextjs(plan: Plan): Record<string, string> {
  const files: Record<string, string> = {};
  const route = (pg: PlanPage) => (pg === plan.pages[0] ? "/" : `/${pg.id}`);
  files["package.json"] = json({
    name: plan.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    private: true,
    version: "0.1.0",
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: { next: "^16.0.0", react: "^19.2.0", "react-dom": "^19.2.0" },
    devDependencies: { typescript: "^5.9.0", "@types/react": "^19.2.0", "@types/node": "^22.0.0" },
  }) + "\n";
  files["next.config.ts"] = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
  files["app/globals.css"] = themeCss(plan);
  files["app/layout.tsx"] = `import type { Metadata } from "next";
import { Layout } from "@/components/Layout";
import "./globals.css";

export const metadata: Metadata = { title: "${plan.appName}", description: "${plan.tagline}" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
`;
  files["components/Layout.tsx"] = layout(plan, route, 'import Link from "next/link";\n', "Link");
  files["components/StatusPill.tsx"] = statusPill();
  files["components/StatCard.tsx"] = statCard();
  files["lib/agents.ts"] = agentsClient(plan, "/api/agents/${agent}/run");
  files["app/api/agents/[id]/route.ts"] = `import { NextResponse } from "next/server";
import { loadAgent } from "@/lib/agent-runtime";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { input, context } = await request.json();
  const agent = await loadAgent(id);
  const run = await agent.run(input, context);
  return NextResponse.json(run);
}
`;
  files["lib/agent-runtime.ts"] = `import { readFile } from "node:fs/promises";
import path from "node:path";

/** Loads an agent definition from agents/<id>.yaml and runs it with the configured framework. */
export async function loadAgent(id: string) {
  const definition = await readFile(path.join(process.cwd(), "agents", \`\${id}.yaml\`), "utf8");
  return {
    definition,
    async run(input: string, context?: unknown) {
      const started = Date.now();
      // Framework adapter goes here (${plan.agents[0]?.framework ?? "Lyzr"} by default).
      return { output: \`\${id} received: \${input}\`, trace: [{ step: "run", ms: Date.now() - started }], context };
    },
  };
}
`;
  for (const c of plan.data) files[`lib/data/${c.id}.ts`] = dataFile(c);
  for (const pg of plan.pages) {
    const dir = pg === plan.pages[0] ? "app" : `app/${pg.id}`;
    files[`${dir}/page.tsx`] = `"use client";\n\n` + pageComponent(pg, plan, { data: "@/lib/data", lib: "@/lib", components: "@/components" });
  }
  return files;
}

function fastapiReact(plan: Plan): Record<string, string> {
  const files = reactVite(plan, "frontend/");
  files["backend/requirements.txt"] = "fastapi==0.118.0\nuvicorn[standard]==0.37.0\npyyaml==6.0.2\npydantic==2.11.0\n";
  files["backend/main.py"] = `from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agents import AGENTS

app = FastAPI(title="${plan.appName}")


class RunRequest(BaseModel):
    input: str
    context: dict | None = None


@app.post("/api/agents/{agent_id}/run")
async def run_agent(agent_id: str, body: RunRequest):
    agent = AGENTS.get(agent_id)
    if agent is None:
        raise HTTPException(status_code=404, detail=f"Unknown agent: {agent_id}")
    return await agent.run(body.input, body.context or {})
`;
  files["backend/agents.py"] = `"""Agents for ${plan.appName}. Definitions live in ../agents/*.yaml."""
from dataclasses import dataclass
from pathlib import Path
import time

import yaml

AGENT_DIR = Path(__file__).resolve().parent.parent / "agents"


@dataclass
class Agent:
    id: str
    name: str
    role: str
    instructions: str
    tools: list[str]

    async def run(self, text: str, context: dict) -> dict:
        started = time.perf_counter()
        # Framework adapter goes here (${plan.agents[0]?.framework ?? "Lyzr"} by default).
        output = f"{self.name} received: {text}"
        return {"output": output, "trace": [{"step": "run", "ms": int((time.perf_counter() - started) * 1000)}]}


def _load(agent_id: str) -> Agent:
    spec = yaml.safe_load((AGENT_DIR / f"{agent_id}.yaml").read_text())
    return Agent(agent_id, spec["name"], spec["role"], spec["instructions"], spec.get("tools") or [])


AGENTS = {${plan.agents.map((a) => `\n    "${a.id}": _load("${a.id}"),`).join("")}
}
`;
  return files;
}

export function generateFiles(plan: Plan, stack: string = "react-vite"): Record<string, string> {
  const s = (["react-vite", "nextjs", "fastapi-react"].includes(stack) ? stack : "react-vite") as Stack;
  const files = s === "nextjs" ? nextjs(plan) : s === "fastapi-react" ? fastapiReact(plan) : reactVite(plan);
  for (const a of plan.agents) files[`agents/${a.id}.yaml`] = agentYaml(a);
  files["README.md"] = readme(plan, s);
  files[".env.example"] = `# Keys for the agent framework and integrations. Never commit real values.\nAGENT_API_KEY=\n${plan.integrations
    .filter((i) => i !== "Knowledge base" && i !== "Web search")
    .map((i) => `${i.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_TOKEN=`)
    .join("\n")}\n`;
  for (const [path, content] of Object.entries(plan.fileOverrides ?? {})) files[path] = content;
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
}
