import { APP_THEMES } from "./themes";
import { editKind, sizePx } from "./visual";
import { agentEntry, agentFiles, agentPackages } from "./agent-code";
import { frameworkLabel, frameworkOf } from "./frameworks";
import { isMcpTool, toolLabel } from "./agents";
import type { Plan, PlanCollection, PlanPage } from "./types";

export { agentEntry, agentFiles } from "./agent-code";

/**
 * Turns a plan into the files of a small but real-looking project. Output is deterministic, so a
 * plan change regenerates exactly the files it affects and the version diff stays honest.
 */

export type Stack = "react-vite" | "nextjs" | "fastapi-react";

const pascal = (s: string) => {
  const p = s
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
  return /^[0-9]/.test(p) ? `Page${p}` : p || "Page";
};
const camel = (s: string) => {
  const p = pascal(s);
  return p[0].toLowerCase() + p.slice(1);
};
const json = (v: unknown) => JSON.stringify(v, null, 2);

function tsType(t: string) {
  return t === "number" || t === "money" ? "number" : "string";
}

// ---------------------------------------------------------------------------------------------
// Shared pieces
// ---------------------------------------------------------------------------------------------

function themeCss(plan: Plan) {
  const t = APP_THEMES[plan.ui.theme];
  const v = t.vars;
  return `/* ${t.label} theme, generated by Architect. Change it from the chat: "use the Midnight theme". */
:root {
  --bg: ${v.bg};
  --surface: ${v.surface};
  --sunken: ${v.sunken};
  --text: ${v.text};
  --muted: ${v.muted};
  --border: ${v.border};
  --accent: ${v.accent};
  --accent-text: ${v.accentText};
  --accent-soft: ${v.accentSoft};
  --success: ${v.success};
  --warning: ${v.warning};
  --danger: ${v.danger};
  --radius: ${t.radius}px;
  --border-width: ${t.borderWidth}px;
  --shadow: ${t.shadow};
  color-scheme: ${t.dark ? "dark" : "light"};
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: "Inter", ui-sans-serif, system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3 {
  font-family: ${t.headingFont === "serif" ? '"Instrument Serif", Georgia, serif' : '"Inter", ui-sans-serif, system-ui, sans-serif'};
  ${t.headingCase === "upper" ? "text-transform: uppercase;\n  letter-spacing: -0.01em;" : "letter-spacing: -0.02em;"}
}

.card {
  background: var(--surface);
  border: var(--border-width) solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}

.button {
  background: var(--accent);
  color: var(--accent-text);
  border: 0;
  border-radius: var(--radius);
  padding: 8px 14px;
  font-weight: 600;
}
${visualEditCss(plan)}`;
}

/** Emphasis and size set with visual edits, as rules on each element's data-edit id. */
function visualEditCss(plan: Plan) {
  const entries = Object.entries(plan.ui.styles ?? {}).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) return "";
  const rules = entries.map(([id, s]) => {
    const kind = editKind(id);
    const decl: string[] = [];
    if (kind === "button") {
      if (s.tone === "muted") decl.push("background: var(--sunken);", "color: var(--text);");
      if (s.tone === "accent") decl.push("box-shadow: 0 0 0 3px var(--accent-soft);");
    } else if (kind === "banner") {
      if (s.tone === "muted") decl.push("background: var(--sunken);", "color: var(--text);", "border-bottom: var(--border-width) solid var(--border);");
    } else if (s.tone) {
      decl.push(`color: var(--${s.tone === "accent" ? "accent" : "muted"});`);
    }
    if (s.size) decl.push(`font-size: ${sizePx(kind, s.size) / 16}rem;`);
    return `[data-edit="${id}"] { ${decl.join(" ")} }`;
  });
  return `\n/* Visual edits */\n${rules.join("\n")}\n`;
}

/** Text a visual edit set on an element with no plan field of its own ("" hides it). */
function label(plan: Plan, id: string, fallback: string) {
  return plan.ui.labels?.[id] ?? fallback;
}

/** Where a page's component lives for a stack. Issues point at this file. */
export function pagePath(plan: Plan, page: PlanPage, stack: string = "react-vite") {
  if (stack === "nextjs") return page.id === plan.pages[0]?.id ? "app/page.tsx" : `app/${page.id}/page.tsx`;
  return `${stack === "fastapi-react" ? "frontend/" : ""}src/pages/${pascal(page.name)}.tsx`;
}

function collectionHookFile() {
  return `import { useEffect, useState } from "react";

type Result<T> = { data: { items?: T[] }; loading: boolean; error: Error | null };

/**
 * Loads a collection from the API. Until the first response arrives, \`data\` is an empty object,
 * so read \`data.items\` defensively.
 */
export function useCollection<T = { id: string }>(name: string): Result<T> {
  const [state, setState] = useState<Result<T>>({ data: {}, loading: true, error: null });

  useEffect(() => {
    let cancelled = false;
    fetch(\`/api/collections/\${name}\`)
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error(\`\${res.status}\`))))
      .then((data) => !cancelled && setState({ data, loading: false, error: null }))
      .catch((error) => !cancelled && setState({ data: {}, loading: false, error }));
    return () => {
      cancelled = true;
    };
  }, [name]);

  return state;
}
`;
}

function usesLiveData(plan: Plan) {
  return plan.pages.some((p) => p.collection && liveState(p, plan) !== "none");
}

/** The line an open issue plants in a page: it maps over items that haven't loaded yet. */
export const BUGGY_LINE = "const live = data.items.map((item) => item.id);";

function dataFile(c: PlanCollection, importPath = "") {
  const typeName = pascal(c.singular);
  const fields = c.fields.map((f) => `  ${f.key}: ${tsType(f.type)};`).join("\n");
  const statusValues = c.statusField ? Array.from(new Set(c.rows.map((r) => String(r[c.statusField!])))).filter(Boolean) : [];
  return `${importPath}export type ${typeName} = {
  id: string;
${fields}
};
${
  statusValues.length
    ? `
export const ${camel(c.singular)}Statuses = ${JSON.stringify(statusValues)} as const;
`
    : ""
}
/** Sample ${c.name.toLowerCase()} so the app has something to show before real data arrives. */
export const ${camel(c.name)}: ${typeName}[] = ${json(c.rows.map((r, i) => ({ id: `${c.id}_${i + 1}`, ...r })))};
`;
}

/** Where each agent is defined and what runs it. The server's runtime picks an adapter per framework. */
function agentRegistry(plan: Plan) {
  if (!plan.agents.length) return "export const AGENTS = {} as const;";
  return `export const AGENTS = {
${plan.agents
  .map((a) => `  ${/^[a-z_$][\w$]*$/i.test(a.id) ? a.id : JSON.stringify(a.id)}: { name: ${JSON.stringify(a.name)}, framework: "${frameworkOf(a.framework).id}", entry: "${agentEntry(a)}" },`)
  .join("\n")}
} as const;`;
}

function agentsClient(plan: Plan, endpoint: string) {
  return `/** Where each agent is defined and what runs it (${[...new Set(plan.agents.map((a) => frameworkLabel(a.framework)))].join(", ") || "no agents yet"}). */
${agentRegistry(plan)}

export type AgentId = keyof typeof AGENTS;

export type AgentRun = {
  output: string;
  trace: { step: string; ms: number }[];
};

/**
 * Runs an agent on the server. Keys stay server-side; the browser only ever sees the output.
 */
export async function runAgent(agent: AgentId, input: string, context?: Record<string, unknown>): Promise<AgentRun> {
  const res = await fetch(\`${endpoint}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ input, context }),
  });
  if (!res.ok) throw new Error(\`Agent \${agent} failed: \${res.status}\`);
  return res.json();
}
`;
}

// ---------------------------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------------------------

/** Whether a page loads live data, and whether that code is still missing its guard. */
function liveState(page: PlanPage, plan: Plan): "none" | "buggy" | "guarded" {
  if (plan.issues?.some((i) => i.pageId === page.id)) return "buggy";
  if (plan.guards?.includes(page.id)) return "guarded";
  return "none";
}

/**
 * Pages that load live data get a few extra lines. With an open issue the code maps over
 * `data.items` before it exists (the crash the preview shows); the fix guards it and adds a
 * loading state, so the version diff reads like a real fix.
 */
function withLiveData(source: string, page: PlanPage, c: PlanCollection, state: "buggy" | "guarded", lib: string) {
  const lines = source.split("\n");
  const lastImport = lines.reduce((at, l, i) => (l.startsWith("import ") ? i : at), -1);
  lines.splice(lastImport + 1, 0, `import { useCollection } from "${lib}/useCollection";`);
  const fn = lines.findIndex((l) => l.startsWith("export default function"));
  const body =
    state === "buggy"
      ? [
          `  // Live ${c.name.toLowerCase()} from the API; the sample rows above are the fallback.`,
          `  const { data } = useCollection("${c.id}");`,
          `  ${BUGGY_LINE}`,
        ]
      : [
          `  // Live ${c.name.toLowerCase()} from the API; the sample rows above are the fallback.`,
          `  const { data, loading } = useCollection("${c.id}");`,
          `  // Items arrive after the first render, so guard the empty state.`,
          `  const live = loading ? [] : (data.items ?? []).map((item) => item.id);`,
        ];
  lines.splice(fn + 1, 0, ...body);
  const headerEnd = lines.findIndex((l) => l.trim() === "</header>");
  const status =
    state === "buggy"
      ? [`        <span className="sync">{live.length} live</span>`]
      : [`        <span className="sync">{loading ? "Loading ${c.name.toLowerCase()}…" : \`\${live.length} live\`}</span>`];
  if (headerEnd > 0) lines.splice(headerEnd, 0, ...status);
  return lines.join("\n");
}

function pageComponent(page: PlanPage, plan: Plan, paths: { data: string; lib: string; components: string }) {
  const source = pageSource(page, plan, paths);
  const c = plan.data.find((d) => d.id === page.collection);
  const state = liveState(page, plan);
  return c && state !== "none" ? withLiveData(source, page, c, state, paths.lib) : source;
}

function pageSource(page: PlanPage, plan: Plan, paths: { data: string; lib: string; components: string }) {
  const name = pascal(page.name);
  const c = plan.data.find((d) => d.id === page.collection) ?? plan.data[0];
  const agent = plan.agents.find((a) => a.id === page.agent) ?? plan.agents[0];
  const dataImport = c ? `import { ${camel(c.name)} } from "${paths.data}/${c.id}";\n` : "";
  const agentImport = agent ? `import { runAgent } from "${paths.lib}/agents";\n` : "";
  const title = label(plan, `title-${page.id}`, page.name);
  const purpose = label(plan, `purpose-${page.id}`, page.purpose);
  const header = `      <header className="page-header">
${title ? `        <h1 data-edit="title-${page.id}">${title}</h1>\n` : ""}${purpose ? `        <p data-edit="purpose-${page.id}">${purpose}</p>\n` : ""}      </header>`;

  switch (page.kind) {
    case "dashboard": {
      const money = c?.fields.find((f) => f.type === "money");
      return `import { useMemo } from "react";
${dataImport}import { StatCard } from "${paths.components}/StatCard";
import { StatusPill } from "${paths.components}/StatusPill";

export default function ${name}() {
  const rows = ${c ? camel(c.name) : "[]"};
  const byStatus = useMemo(() => {
    const counts = new Map<string, number>();
    for (const row of rows) counts.set(${c?.statusField ? `row.${c.statusField}` : '"All"'}, (counts.get(${c?.statusField ? `row.${c.statusField}` : '"All"'}) ?? 0) + 1);
    return [...counts.entries()];
  }, [rows]);

  return (
    <div className="page">
${header}
      <section className="stats">
        <StatCard data-edit="stat-${page.id}-0" label="${label(plan, `stat-${page.id}-0`, `Total ${c?.name.toLowerCase() ?? "items"}`)}" value={rows.length} />
${byStatus_tiles(plan, page, c)}${money ? `        <StatCard data-edit="stat-${page.id}-2" label="${label(plan, `stat-${page.id}-2`, `Total ${money.label.toLowerCase()}`)}" value={rows.reduce((sum, r) => sum + r.${money.key}, 0)} format="money" />\n` : ""}      </section>

      <section className="card">
        <h2 data-edit="card-${page.id}-1">${label(plan, `card-${page.id}-1`, `By ${c?.statusField ?? "status"}`)}</h2>
        <ul className="bars">
          {byStatus.map(([status, count]) => (
            <li key={status}>
              <StatusPill value={status} />
              <span className="bar" style={{ width: \`\${(count / rows.length) * 100}%\` }} />
              <span>{count}</span>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
`;
    }
    case "list": {
      const cols = c?.fields.slice(0, 5) ?? [];
      return `import { useMemo, useState } from "react";
${dataImport}${agentImport}import { StatusPill } from "${paths.components}/StatusPill";

export default function ${name}() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [answer, setAnswer] = useState<string>("");

  const rows = useMemo(
    () =>
      ${c ? camel(c.name) : "[]"}.filter((row) =>
        Object.values(row).some((value) => String(value).toLowerCase().includes(query.toLowerCase())),
      ),
    [query],
  );

  async function ask(id: string) {
    setSelected(id);
    const row = rows.find((r) => r.id === id);
    ${agent ? `const run = await runAgent("${agent.id}", "Summarise this ${c?.singular.toLowerCase() ?? "item"} and suggest the next step.", { row });
    setAnswer(run.output);` : "setAnswer(JSON.stringify(row));"}
  }

  return (
    <div className="page">
${header}
${plan.ui.search ? `      <input className="search" placeholder="Search ${c?.name.toLowerCase() ?? "items"}" value={query} onChange={(e) => setQuery(e.target.value)} />\n` : ""}      <table className="card table">
        <thead>
          <tr>
${cols.map((f) => `            <th>${f.label}</th>`).join("\n")}
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id} onClick={() => ask(row.id)} aria-selected={selected === row.id}>
${cols.map((f) => (f.type === "status" ? `              <td><StatusPill value={row.${f.key}} /></td>` : `              <td>{row.${f.key}}</td>`)).join("\n")}
            </tr>
          ))}
        </tbody>
      </table>

      {answer && <aside className="card answer">{answer}</aside>}
    </div>
  );
}
`;
    }
    case "workbench":
      return `import { useState } from "react";
${dataImport}${agentImport}
export default function ${name}() {
  const items = ${c ? camel(c.name) : "[]"};
  const [current, setCurrent] = useState(items[0]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);

  async function generate() {
    setBusy(true);
    const run = await runAgent("${agent?.id ?? "assistant"}", "Draft a response for this ${c?.singular.toLowerCase() ?? "item"}.", { item: current });
    setDraft(run.output);
    setBusy(false);
  }

  return (
    <div className="page workbench">
${header}
      <nav className="card list">
        {items.map((item) => (
          <button key={item.id} onClick={() => setCurrent(item)} aria-current={item.id === current?.id}>
            {item.${c?.titleField ?? "id"}}
          </button>
        ))}
      </nav>
      <section className="card">
        <h2>{current?.${c?.titleField ?? "id"}}</h2>
        <button className="button" onClick={generate} disabled={busy}>
          {busy ? "${agent?.name ?? "Agent"} is writing…" : "Draft with ${agent?.name ?? "the agent"}"}
        </button>
        <textarea value={draft} onChange={(e) => setDraft(e.target.value)} rows={12} />
        <div className="actions">
          <button className="button">Approve</button>
          <button onClick={generate}>Regenerate</button>
        </div>
      </section>
    </div>
  );
}
`;
    case "chat":
      return `import { useState } from "react";
${agentImport}
type Message = { role: "user" | "agent"; text: string };

export default function ${name}() {
  const [messages, setMessages] = useState<Message[]>([
    { role: "agent", text: "Hi! I'm ${agent?.name ?? "your assistant"}. ${agent?.role ?? ""}" },
  ]);
  const [input, setInput] = useState("");

  async function send() {
    const text = input.trim();
    if (!text) return;
    setMessages((m) => [...m, { role: "user", text }]);
    setInput("");
    const run = await runAgent("${agent?.id ?? "assistant"}", text);
    setMessages((m) => [...m, { role: "agent", text: run.output }]);
  }

  return (
    <div className="page chat">
${header}
      <ol className="messages">
        {messages.map((m, i) => (
          <li key={i} className={m.role}>{m.text}</li>
        ))}
      </ol>
      <form onSubmit={(e) => { e.preventDefault(); send(); }}>
        <input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask ${agent?.name ?? "the assistant"} anything…" />
        <button className="button">Send</button>
      </form>
    </div>
  );
}
`;
    case "run": {
      const pipeline = plan.agents.map((a) => `"${a.id}"`).join(", ");
      return `import { useState } from "react";
${agentImport}
const PIPELINE = [${pipeline}] as const;

export default function ${name}() {
  const [input, setInput] = useState("");
  const [step, setStep] = useState<number | null>(null);
  const [result, setResult] = useState("");

  async function run() {
    let context = input;
    for (let i = 0; i < PIPELINE.length; i++) {
      setStep(i);
      const out = await runAgent(PIPELINE[i], context);
      context = out.output;
    }
    setStep(null);
    setResult(context);
  }

  return (
    <div className="page">
${header}
      <label className="card field">
        <span>${page.input?.label ?? "Input"}</span>
        <textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="${page.input?.placeholder ?? ""}" rows={5} />
      </label>
      <button className="button" onClick={run} disabled={!input || step !== null}>
        {step === null ? "${page.input?.cta ?? "Run"}" : \`Running \${PIPELINE[step]}…\`}
      </button>
      {result && <article className="card result">{result}</article>}
    </div>
  );
}
`;
    }
    case "settings":
      return `const INTEGRATIONS = ${JSON.stringify(plan.integrations)};

export default function ${name}() {
  return (
    <div className="page">
${header}
      <section className="card">
        <h2 data-edit="card-${page.id}-0">${label(plan, `card-${page.id}-0`, "Connections")}</h2>
        <ul>
          {INTEGRATIONS.map((name) => (
            <li key={name}>
              {name} <button>Manage</button>
            </li>
          ))}
        </ul>
      </section>
      <section className="card">
        <h2 data-edit="card-${page.id}-1">${label(plan, `card-${page.id}-1`, "Notifications")}</h2>
        <label><input type="checkbox" defaultChecked /> Email me a daily summary</label>
        <label><input type="checkbox" /> Notify me when an agent needs approval</label>
      </section>
    </div>
  );
}
`;
  }
}

function byStatus_tiles(plan: Plan, page: PlanPage, c?: PlanCollection) {
  if (!c?.statusField) return "";
  const first = String(c.rows[0]?.[c.statusField] ?? "");
  if (!first) return "";
  return `        <StatCard data-edit="stat-${page.id}-1" label="${label(plan, `stat-${page.id}-1`, first)}" value={rows.filter((r) => r.${c.statusField} === "${first}").length} tone="accent" />\n`;
}

function statusPill() {
  return `const TONES: Record<string, string> = {
  urgent: "danger", high: "danger", overdue: "danger", exception: "danger", blocked: "danger", rejected: "danger",
  done: "success", paid: "success", sent: "success", mastered: "success", ok: "success", indexed: "success", clean: "success",
  "in progress": "warning", review: "warning", "needs review": "warning", learning: "warning", medium: "warning",
};

export function StatusPill({ value }: { value: string }) {
  const tone = TONES[value.toLowerCase()] ?? "neutral";
  return <span className={\`pill pill-\${tone}\`}>{value}</span>;
}
`;
}

function statCard() {
  return `const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

type Props = { label: string; value: number; format?: "money"; tone?: "accent"; "data-edit"?: string };

export function StatCard({ label, value, format, tone, ...rest }: Props) {
  return (
    <div className={\`card stat \${tone ?? ""}\`} {...rest}>
      <span>{label}</span>
      <strong>{format === "money" ? money.format(value) : value}</strong>
    </div>
  );
}
`;
}

function layout(plan: Plan, routeFor: (p: PlanPage) => string, linkImport: string, linkTag: "Link" | "NavLink") {
  return `${linkImport}
const NAV = [
${plan.pages
  .filter((p) => label(plan, `nav-${p.id}`, p.name) !== "")
  .map((p) => `  { id: "${p.id}", to: "${routeFor(p)}", label: "${p.name}" },`)
  .join("\n")}
];

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="app">
      <aside className="sidebar">
        <strong className="brand" data-edit="app-name">${plan.appName}</strong>
        <nav>
          {NAV.map((item) => (
            <${linkTag} key={item.to} ${linkTag === "Link" ? "href" : "to"}={item.to} data-edit={\`nav-\${item.id}\`}>
              {item.label}
            </${linkTag}>
          ))}
        </nav>
      </aside>
      <main>
${plan.ui.banner ? `        <div className="banner" data-edit="banner">${plan.ui.banner}</div>\n` : ""}        {children}
      </main>
    </div>
  );
}
`;
}

function readme(plan: Plan, stack: Stack) {
  const run =
    stack === "fastapi-react"
      ? "```bash\ncd backend && pip install -r requirements.txt && uvicorn main:app --reload\ncd frontend && npm install && npm run dev\n```"
      : "```bash\nnpm install\nnpm run dev\n```";
  return `# ${plan.appName}

${plan.tagline}

${plan.overview}

## Pages

${plan.pages.map((p) => `- **${p.name}**: ${p.purpose}`).join("\n")}

## Agents

| Agent | Role | Framework | Tools |
| --- | --- | --- | --- |
${plan.agents.map((a) => `| ${a.name} | ${a.role} | ${frameworkLabel(a.framework)} | ${a.tools.map(toolLabel).join(", ") || "none"} |`).join("\n")}

## Run it locally

${run}

Agent definitions live in \`agents/\`${plan.agents.some((a) => frameworkOf(a.framework).id === "mastra") ? " and `src/mastra/agents/`" : ""}, one per agent in its own framework. Built with Architect.
`;
}

// ---------------------------------------------------------------------------------------------
// Stacks
// ---------------------------------------------------------------------------------------------

function reactVite(plan: Plan, base = ""): Record<string, string> {
  const files: Record<string, string> = {};
  const p = (path: string) => `${base}${path}`;
  const route = (pg: PlanPage) => (pg === plan.pages[0] ? "/" : `/${pg.id}`);

  files[p("package.json")] = json({
    name: plan.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    private: true,
    version: "0.1.0",
    type: "module",
    scripts: { dev: "vite", build: "tsc -b && vite build", preview: "vite preview" },
    dependencies: { react: "^19.2.0", "react-dom": "^19.2.0", "react-router-dom": "^7.9.0" },
    devDependencies: { "@vitejs/plugin-react": "^5.0.0", typescript: "^5.9.0", vite: "^7.1.0" },
  }) + "\n";
  files[p("index.html")] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${plan.appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  files[p("vite.config.ts")] = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { proxy: { "/api": "http://localhost:8000" } },
});
`;
  files[p("tsconfig.json")] = json({
    compilerOptions: { target: "ES2022", lib: ["ES2022", "DOM"], jsx: "react-jsx", module: "ESNext", moduleResolution: "bundler", strict: true, skipLibCheck: true },
    include: ["src"],
  }) + "\n";
  files[p("src/main.tsx")] = `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./theme.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
`;
  files[p("src/App.tsx")] = `import { Route, Routes } from "react-router-dom";
import { Layout } from "./components/Layout";
${plan.pages.map((pg) => `import ${pascal(pg.name)} from "./pages/${pascal(pg.name)}";`).join("\n")}

export default function App() {
  return (
    <Layout>
      <Routes>
${plan.pages.map((pg) => `        <Route path="${route(pg)}" element={<${pascal(pg.name)} />} />`).join("\n")}
      </Routes>
    </Layout>
  );
}
`;
  files[p("src/theme.css")] = themeCss(plan);
  files[p("src/components/Layout.tsx")] = layout(plan, route, 'import { NavLink } from "react-router-dom";\n', "NavLink");
  files[p("src/components/StatusPill.tsx")] = statusPill();
  files[p("src/components/StatCard.tsx")] = statCard();
  files[p("src/lib/agents.ts")] = agentsClient(plan, "/api/agents/${agent}/run");
  if (usesLiveData(plan)) files[p("src/lib/useCollection.ts")] = collectionHookFile();
  for (const c of plan.data) files[p(`src/data/${c.id}.ts`)] = dataFile(c);
  for (const pg of plan.pages) {
    files[p(`src/pages/${pascal(pg.name)}.tsx`)] = pageComponent(pg, plan, { data: "../data", lib: "../lib", components: "../components" });
  }
  return files;
}

function nextjs(plan: Plan): Record<string, string> {
  const files: Record<string, string> = {};
  const route = (pg: PlanPage) => (pg === plan.pages[0] ? "/" : `/${pg.id}`);
  files["package.json"] = json({
    name: plan.appName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    private: true,
    version: "0.1.0",
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: { next: "^16.0.0", react: "^19.2.0", "react-dom": "^19.2.0" },
    devDependencies: { typescript: "^5.9.0", "@types/react": "^19.2.0", "@types/node": "^22.0.0" },
  }) + "\n";
  files["next.config.ts"] = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
  files["app/globals.css"] = themeCss(plan);
  files["app/layout.tsx"] = `import type { Metadata } from "next";
import { Layout } from "@/components/Layout";
import "./globals.css";

export const metadata: Metadata = { title: "${plan.appName}", description: "${plan.tagline}" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
`;
  files["components/Layout.tsx"] = layout(plan, route, 'import Link from "next/link";\n', "Link");
  files["components/StatusPill.tsx"] = statusPill();
  files["components/StatCard.tsx"] = statCard();
  files["lib/agents.ts"] = agentsClient(plan, "/api/agents/${agent}/run");
  if (usesLiveData(plan)) files["lib/useCollection.ts"] = collectionHookFile();
  files["app/api/agents/[id]/route.ts"] = `import { NextResponse } from "next/server";
import { runAgent } from "@/lib/agent-runtime";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { input, context } = await request.json();
  const run = await runAgent(id, input, context);
  if (!run) return NextResponse.json({ error: \`Unknown agent: \${id}\` }, { status: 404 });
  return NextResponse.json(run);
}
`;
  files["lib/agent-runtime.ts"] = agentRuntime(plan);
  for (const c of plan.data) files[`lib/data/${c.id}.ts`] = dataFile(c);
  for (const pg of plan.pages) {
    const dir = pg === plan.pages[0] ? "app" : `app/${pg.id}`;
    files[`${dir}/page.tsx`] = `"use client";\n\n` + pageComponent(pg, plan, { data: "@/lib/data", lib: "@/lib", components: "@/components" });
  }
  return files;
}

function fastapiReact(plan: Plan): Record<string, string> {
  const files = reactVite(plan, "frontend/");
  files["backend/requirements.txt"] = "fastapi==0.118.0\nuvicorn[standard]==0.37.0\npyyaml==6.0.2\npydantic==2.11.0\n";
  files["backend/main.py"] = `from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agents import AGENTS

app = FastAPI(title="${plan.appName}")


class RunRequest(BaseModel):
    input: str
    context: dict | None = None


@app.post("/api/agents/{agent_id}/run")
async def run_agent(agent_id: str, body: RunRequest):
    agent = AGENTS.get(agent_id)
    if agent is None:
        raise HTTPException(status_code=404, detail=f"Unknown agent: {agent_id}")
    return await agent.run(body.input, body.context or {})
`;
  files["backend/agents.py"] = pythonRuntime(plan);
  return files;
}


// ---------------------------------------------------------------------------------------------
// Agent runtime and dependencies
// ---------------------------------------------------------------------------------------------

const PY_FRAMEWORKS = new Set(["langgraph", "crewai", "google-adk"]);
const TS_FRAMEWORKS = new Set(["openai-agents", "claude-agent-sdk", "mastra"]);

function usedFrameworks(plan: Plan) {
  return [...new Set(plan.agents.map((a) => frameworkOf(a.framework).id))];
}

/** Next.js: one adapter per framework the plan uses. Hosted ones call Lyzr; code-first ones import the agent. */
function agentRuntime(plan: Plan) {
  const used = usedFrameworks(plan);
  const lines: string[] = [];
  for (const f of used) {
    const key = /^[a-z]+$/.test(f) ? f : JSON.stringify(f);
    if (f === "lyzr" || f === "gitagent") lines.push(`  ${key}: (agent, input, context) => runHosted(agent.entry, input, context),`);
    else if (PY_FRAMEWORKS.has(f)) lines.push(`  ${key}: (agent, input, context) => runPython(agent.entry, input, context),`);
    else lines.push(`  ${key}: async (agent, input) => ({ output: await (await import(\`@/\${agent.entry.replace(/\\.ts$/, "")}\`)).run(input), trace: [] }),`);
  }
  const hosted = used.some((f) => f === "lyzr" || f === "gitagent");
  const python = used.some((f) => PY_FRAMEWORKS.has(f));
  return `import { AGENTS, type AgentId } from "./agents";

type Run = { output: string; trace: { step: string; ms: number }[] };
type Adapter = (agent: (typeof AGENTS)[AgentId], input: string, context?: unknown) => Promise<Run>;

/** One adapter per framework this project uses: ${used.map((f) => frameworkLabel(f)).join(", ") || "none yet"}. */
const adapters: Partial<Record<string, Adapter>> = {
${lines.join("\n")}
};
${
  hosted
    ? `
/** Lyzr and GitAgent agents run hosted, from the definition in this repo. */
async function runHosted(entry: string, input: string, context?: unknown): Promise<Run> {
  const res = await fetch(\`\${process.env.LYZR_RUNTIME_URL}/run\`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: \`Bearer \${process.env.AGENT_API_KEY}\` },
    body: JSON.stringify({ definition: entry, input, context }),
  });
  if (!res.ok) throw new Error(\`Hosted run failed: \${res.status}\`);
  return res.json();
}
`
    : ""
}${
  python
    ? `
/** Python agents (LangGraph, CrewAI, Google ADK) run in a small worker next to this app. */
async function runPython(entry: string, input: string, context?: unknown): Promise<Run> {
  const res = await fetch(\`\${process.env.PYTHON_WORKER_URL}/run\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ module: entry.replace(/\\/agent\\.py$|\\.py$/, "").replaceAll("/", "."), input, context }),
  });
  if (!res.ok) throw new Error(\`Python worker failed: \${res.status}\`);
  return res.json();
}
`
    : ""
}
export async function runAgent(id: string, input: string, context?: unknown): Promise<Run | null> {
  const agent = AGENTS[id as AgentId];
  if (!agent) return null;
  const adapter = adapters[agent.framework];
  if (!adapter) throw new Error(\`No adapter for \${agent.framework}\`);
  const started = Date.now();
  const run = await adapter(agent, input, context);
  return { ...run, trace: [...run.trace, { step: "total", ms: Date.now() - started }] };
}
`;
}

/** FastAPI: Python agents are imported directly; hosted and TypeScript ones are called over HTTP. */
function pythonRuntime(plan: Plan) {
  const rows = plan.agents.map((a) => `    "${a.id}": Agent("${a.id}", ${JSON.stringify(a.name)}, "${frameworkOf(a.framework).id}", "${agentEntry(a)}"),`);
  return `"""Agents for ${plan.appName}: ${[...new Set(plan.agents.map((a) => frameworkLabel(a.framework)))].join(", ") || "none yet"}."""
from dataclasses import dataclass
import importlib
import os
import time

import httpx

PYTHON_FRAMEWORKS = {"langgraph", "crewai", "google-adk"}


@dataclass
class Agent:
    id: str
    name: str
    framework: str
    entry: str

    async def run(self, text: str, context: dict) -> dict:
        started = time.perf_counter()
        if self.framework in PYTHON_FRAMEWORKS:
            module = importlib.import_module(self.entry.removesuffix("/agent.py").removesuffix(".py").replace("/", "."))
            output = module.run(text) if hasattr(module, "run") else str(module.root_agent)
        else:
            # Lyzr and GitAgent run hosted; TypeScript agents run in the Node worker.
            url = os.environ["LYZR_RUNTIME_URL" if self.framework in {"lyzr", "gitagent"} else "NODE_WORKER_URL"]
            async with httpx.AsyncClient(timeout=60) as client:
                res = await client.post(f"{url}/run", json={"definition": self.entry, "input": text, "context": context})
                res.raise_for_status()
                output = res.json()["output"]
        return {"output": output, "trace": [{"step": self.framework, "ms": int((time.perf_counter() - started) * 1000)}]}


AGENTS = {
${rows.join("\n")}
}
`;
}

function mergePackageJson(source: string, packages: string[]) {
  const pkg = JSON.parse(source) as { dependencies?: Record<string, string> };
  const deps = { ...(pkg.dependencies ?? {}) };
  for (const spec of packages) {
    const at = spec.lastIndexOf("@");
    deps[spec.slice(0, at)] = spec.slice(at + 1);
  }
  pkg.dependencies = Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));
  return json(pkg) + "\n";
}

/** Framework SDKs go into the generated project's own manifests, never Architect's. */
function addAgentPackages(files: Record<string, string>, plan: Plan, stack: Stack) {
  const { python, node } = agentPackages(plan);
  const pkgPath = stack === "fastapi-react" ? "frontend/package.json" : "package.json";
  if (node.length && files[pkgPath]) files[pkgPath] = mergePackageJson(files[pkgPath], node);
  if (!python.length) return;
  if (stack === "fastapi-react") {
    const have = new Set(files["backend/requirements.txt"].trim().split("\n"));
    files["backend/requirements.txt"] = [...have, ...python.filter((p) => !have.has(p))].join("\n") + "\n";
  } else {
    files["agents/requirements.txt"] = `# Python agents in this folder (${usedFrameworks(plan)
      .filter((f) => PY_FRAMEWORKS.has(f))
      .map((f) => frameworkLabel(f))
      .join(", ")}). Install with: pip install -r agents/requirements.txt\n${python.join("\n")}\n`;
  }
}

function envExample(plan: Plan) {
  const used = usedFrameworks(plan);
  const lines = ["# Keys for the agent frameworks and integrations. Never commit real values.", "AGENT_API_KEY="];
  if (used.some((f) => f === "lyzr" || f === "gitagent")) lines.push("LYZR_RUNTIME_URL=");
  if (used.some((f) => PY_FRAMEWORKS.has(f) || TS_FRAMEWORKS.has(f))) lines.push("ANTHROPIC_API_KEY=", "ARCHITECT_TOOLS_URL=");
  if (used.some((f) => PY_FRAMEWORKS.has(f))) lines.push("PYTHON_WORKER_URL=");
  for (const i of plan.integrations.filter((i) => i !== "Knowledge base" && i !== "Web search")) lines.push(`${i.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_TOKEN=`);
  const mcp = [...new Set(plan.agents.flatMap((a) => a.tools.filter(isMcpTool).map(toolLabel)))];
  for (const m of mcp) lines.push(`${m.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_MCP_URL=`);
  return [...new Set(lines)].join("\n") + "\n";
}

export function generateFiles(plan: Plan, stack: string = "react-vite"): Record<string, string> {
  const s = (["react-vite", "nextjs", "fastapi-react"].includes(stack) ? stack : "react-vite") as Stack;
  const files = s === "nextjs" ? nextjs(plan) : s === "fastapi-react" ? fastapiReact(plan) : reactVite(plan);
  for (const a of plan.agents) Object.assign(files, agentFiles(a, plan));
  addAgentPackages(files, plan, s);
  files["README.md"] = readme(plan, s);
  files[".env.example"] = envExample(plan);
  for (const [path, content] of Object.entries(plan.fileOverrides ?? {})) {
    if (content === null) delete files[path];
    else files[path] = content;
  }
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
}
